<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Books Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 20px;
        }
        h1 {
            text-align: center;
            color: #1f2937;
            margin-bottom: 10px;
        }
        .export-date {
            text-align: center;
            font-size: 12px;
            color: #6b7280;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table thead {
            background-color: #f3f4f6;
            border-bottom: 2px solid #d1d5db;
        }
        table thead th {
            padding: 12px;
            text-align: left;
            font-weight: bold;
            color: #1f2937;
            font-size: 12px;
        }
        table tbody td {
            padding: 10px 12px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 11px;
        }
        table tbody tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .category-badge {
            display: inline-block;
            background-color: #dbeafe;
            color: #1e40af;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: 500;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 11px;
            color: #9ca3af;
            border-top: 1px solid #e5e7eb;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <h1>Books Inventory Report</h1>
    <div class="export-date">
        Generated on {{ now()->format('F d, Y H:i:s') }}
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%">#</th>
                <th style="width: 20%">Title</th>
                <th style="width: 15%">Author</th>
                <th style="width: 15%">ISBN</th>
                <th style="width: 20%">Category</th>
                <th style="width: 25%">Added On</th>
            </tr>
        </thead>
        <tbody>
            @forelse($books as $book)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td><strong>{{ $book->title }}</strong></td>
                    <td>{{ $book->author }}</td>
                    <td>{{ $book->isbn }}</td>
                    <td>
                        <span class="category-badge">
                            {{ $book->category ? $book->category->name : 'N/A' }}
                        </span>
                    </td>
                    <td>{{ $book->created_at->format('M d, Y') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; padding: 20px;">
                        No books found with the selected filters.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Total Records: {{ count($books) }} | Report Generated by Books Management System</p>
    </div>
</body>
</html>
